# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('neighborhood', models.CharField(max_length=255)),
            ],
        ),
    ]
