# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='avg_sale_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='high_sale_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='lowest_sale_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='med_sale_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='num_of_sales',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='type_of_home',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='year',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
