# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streetAddress', models.CharField(max_length=200)),
                ('borough', models.CharField(max_length=65)),
                ('state', models.CharField(max_length=65)),
                ('zip', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('neighborhood', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=30)),
                ('type_of_home', models.PositiveSmallIntegerField(null=True)),
                ('num_of_sales', models.PositiveSmallIntegerField(null=True)),
                ('lowest_sale_price', models.FloatField(null=True)),
                ('avg_sale_price', models.FloatField(null=True)),
                ('med_sale_price', models.FloatField(null=True)),
                ('high_sale_price', models.FloatField(null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sales', to='appreciation.Property')),
            ],
        ),
    ]
